import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import ThemeContextProvider from "@/context/ThemeContext";
import ThemeSwitch from "@/components/theme-switch";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <ThemeRegistry>
            <ThemeSwitch />
            <Toaster/>
            {children}
          </ThemeRegistry>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
